language: python
cache:
  - pip
  - apt
python:
  - "2.7"
branches:
  only:
    - master
install:
  - "pip install -r codalab/requirements/dev_azure_nix.txt"
#  - "pip install -q flake8 pylint django-nose"
before_script:
#  - "flake8 --config=.flake8 ."
#  - "pylint --rcfile=pylint.rc tests"
#  - "pylint --rcfile=pylint.rc setup.py"
script:
  - "cd codalab"
  - "python manage.py test"
notifications:
  slack: tivix:R2rmqmHoOvRo0pgfL7g7Sly6
